// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5NXkKXuobnILmHELW2FjVtbGpTN_LMNE',
    appId: '1:651436841013:web:ab124be9570ecc0896397c',
    messagingSenderId: '651436841013',
    projectId: 'movies-aabf2',
    authDomain: 'movies-aabf2.firebaseapp.com',
    storageBucket: 'movies-aabf2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4auJlG6QWFowWgHXwr6JkXBNIMokFTYQ',
    appId: '1:651436841013:android:3cdd8b5401ec769d96397c',
    messagingSenderId: '651436841013',
    projectId: 'movies-aabf2',
    storageBucket: 'movies-aabf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu6WaLW-4Eb2axTD0_9RIswSxT0h8vaJI',
    appId: '1:651436841013:ios:cfc9bbc18fff070296397c',
    messagingSenderId: '651436841013',
    projectId: 'movies-aabf2',
    storageBucket: 'movies-aabf2.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu6WaLW-4Eb2axTD0_9RIswSxT0h8vaJI',
    appId: '1:651436841013:ios:cfc9bbc18fff070296397c',
    messagingSenderId: '651436841013',
    projectId: 'movies-aabf2',
    storageBucket: 'movies-aabf2.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5NXkKXuobnILmHELW2FjVtbGpTN_LMNE',
    appId: '1:651436841013:web:7955e392c779506696397c',
    messagingSenderId: '651436841013',
    projectId: 'movies-aabf2',
    authDomain: 'movies-aabf2.firebaseapp.com',
    storageBucket: 'movies-aabf2.firebasestorage.app',
  );
}
